// IPL 2026 Official Squads Part B: MI, PBKS, RR, RCB, SRH
(function(){
const S={
MI:[
{id:"rohit_mi",name:"Rohit Sharma",role:"Batsman",nat:"IND",bat:88,bowl:5},
{id:"sky_mi",name:"Suryakumar Yadav",role:"Batsman",nat:"IND",bat:93,bowl:5},
{id:"robin_mi",name:"Robin Minz",role:"WK-Batsman",nat:"IND",bat:68,bowl:0},
{id:"rick_mi",name:"Ryan Rickelton",role:"WK-Batsman",nat:"SA",bat:80,bowl:0},
{id:"tilak_mi",name:"Tilak Varma",role:"Batsman",nat:"IND",bat:84,bowl:8},
{id:"pandya_mi",name:"Hardik Pandya",role:"All-Rounder",nat:"IND",bat:80,bowl:79,isCaptain:true},
{id:"naman_mi",name:"Naman Dhir",role:"All-Rounder",nat:"IND",bat:72,bowl:62},
{id:"santner_mi",name:"Mitchell Santner",role:"All-Rounder",nat:"NZ",bat:52,bowl:79},
{id:"jacks_mi",name:"Will Jacks",role:"All-Rounder",nat:"ENG",bat:76,bowl:72},
{id:"bosch_mi",name:"Corbin Bosch",role:"All-Rounder",nat:"SA",bat:68,bowl:73},
{id:"bawa_mi",name:"Raj Bawa",role:"All-Rounder",nat:"IND",bat:66,bowl:64},
{id:"boult_mi",name:"Trent Boult",role:"Pacer",nat:"NZ",bat:15,bowl:89},
{id:"bumrah_mi",name:"Jasprit Bumrah",role:"Pacer",nat:"IND",bat:12,bowl:98},
{id:"chahar_mi",name:"Deepak Chahar",role:"Pacer",nat:"IND",bat:30,bowl:83},
{id:"ashwani_mi",name:"Ashwani Kumar",role:"Pacer",nat:"IND",bat:10,bowl:72},
{id:"raghu_mi",name:"Raghu Sharma",role:"Pacer",nat:"IND",bat:12,bowl:70},
{id:"ghazanfar_mi",name:"Allah Ghazanfar",role:"Spinner",nat:"AFG",bat:15,bowl:82},
{id:"markande_mi",name:"Mayank Markande",role:"Spinner",nat:"IND",bat:22,bowl:74},
{id:"shardul_mi",name:"Shardul Thakur",role:"All-Rounder",nat:"IND",bat:58,bowl:79},
{id:"rutherford_mi",name:"Sherfane Rutherford",role:"Batsman",nat:"WI",bat:76,bowl:15},
{id:"dekock_mi",name:"Quinton de Kock",role:"WK-Batsman",nat:"SA",bat:86,bowl:0},
{id:"ankolekar_mi",name:"Atharva Ankolekar",role:"All-Rounder",nat:"IND",bat:45,bowl:70},
{id:"izhar_mi",name:"Mohammad Izhar",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"danish_mi",name:"Danish Malewar",role:"Batsman",nat:"IND",bat:62,bowl:5},
{id:"mayankR_mi",name:"Mayank Rawat",role:"All-Rounder",nat:"IND",bat:55,bowl:60},
],PBKS:[
{id:"shreyas_pbks",name:"Shreyas Iyer",role:"Batsman",nat:"IND",bat:84,bowl:5,isCaptain:true},
{id:"nehal_pbks",name:"Nehal Wadhera",role:"Batsman",nat:"IND",bat:72,bowl:5},
{id:"vishnu_pbks",name:"Vishnu Vinod",role:"WK-Batsman",nat:"IND",bat:68,bowl:0},
{id:"harnoor_pbks",name:"Harnoor Pannu",role:"Batsman",nat:"IND",bat:68,bowl:5},
{id:"pyla_pbks",name:"Pyla Avinash",role:"Batsman",nat:"IND",bat:64,bowl:5},
{id:"prabhs_pbks",name:"Prabhsimran Singh",role:"WK-Batsman",nat:"IND",bat:81,bowl:0},
{id:"shashank_pbks",name:"Shashank Singh",role:"Batsman",nat:"IND",bat:80,bowl:5},
{id:"stoinis_pbks",name:"Marcus Stoinis",role:"All-Rounder",nat:"AUS",bat:80,bowl:73},
{id:"harpreet_pbks",name:"Harpreet Brar",role:"All-Rounder",nat:"IND",bat:58,bowl:74},
{id:"jansen_pbks",name:"Marco Jansen",role:"All-Rounder",nat:"SA",bat:42,bowl:82},
{id:"omarzai_pbks",name:"Azmatullah Omarzai",role:"All-Rounder",nat:"AFG",bat:72,bowl:75},
{id:"priyansh_pbks",name:"Priyansh Arya",role:"All-Rounder",nat:"IND",bat:72,bowl:25},
{id:"musheer_pbks",name:"Musheer Khan",role:"All-Rounder",nat:"IND",bat:72,bowl:50},
{id:"suryansh_pbks",name:"Suryansh Shedge",role:"All-Rounder",nat:"IND",bat:65,bowl:50},
{id:"owen_pbks",name:"Mitch Owen",role:"All-Rounder",nat:"AUS",bat:70,bowl:35},
{id:"arsh_pbks",name:"Arshdeep Singh",role:"Pacer",nat:"IND",bat:22,bowl:85},
{id:"chahal_pbks",name:"Yuzvendra Chahal",role:"Spinner",nat:"IND",bat:12,bowl:90},
{id:"vyshak_pbks",name:"Vyshak Vijaykumar",role:"Pacer",nat:"IND",bat:15,bowl:77},
{id:"yashT_pbks",name:"Yash Thakur",role:"Pacer",nat:"IND",bat:12,bowl:75},
{id:"bartlett_pbks",name:"Xavier Bartlett",role:"Pacer",nat:"AUS",bat:18,bowl:79},
{id:"ferguson_pbks",name:"Lockie Ferguson",role:"Pacer",nat:"NZ",bat:12,bowl:83},
{id:"connolly_pbks",name:"Cooper Connolly",role:"All-Rounder",nat:"AUS",bat:62,bowl:65},
{id:"dwarshuis_pbks",name:"Ben Dwarshuis",role:"All-Rounder",nat:"AUS",bat:35,bowl:76},
{id:"vishal_pbks",name:"Vishal Nishad",role:"Pacer",nat:"IND",bat:8,bowl:72},
{id:"pravin_pbks",name:"Pravin Dubey",role:"Pacer",nat:"IND",bat:10,bowl:73},
],RR:[
{id:"jaiswal_rr",name:"Yashasvi Jaiswal",role:"Batsman",nat:"IND",bat:90,bowl:5},
{id:"parag_rr",name:"Riyan Parag",role:"Batsman",nat:"IND",bat:80,bowl:65,isCaptain:true},
{id:"dubey_rr",name:"Shubham Dubey",role:"Batsman",nat:"IND",bat:70,bowl:65},
{id:"sooryav_rr",name:"Vaibhav Sooryavanshi",role:"Batsman",nat:"IND",bat:72,bowl:5},
{id:"pretorius_rr",name:"Lhuan-dre Pretorius",role:"Batsman",nat:"SA",bat:76,bowl:5},
{id:"hetmyer_rr",name:"Shimron Hetmyer",role:"Batsman",nat:"WI",bat:84,bowl:5},
{id:"jurel_rr",name:"Dhruv Jurel",role:"WK-Batsman",nat:"IND",bat:76,bowl:0},
{id:"yudhvir_rr",name:"Yudhvir Singh Charak",role:"All-Rounder",nat:"IND",bat:52,bowl:68},
{id:"archer_rr",name:"Jofra Archer",role:"Pacer",nat:"ENG",bat:30,bowl:91},
{id:"deshpande_rr",name:"Tushar Deshpande",role:"Pacer",nat:"IND",bat:15,bowl:79},
{id:"sandeep_rr",name:"Sandeep Sharma",role:"Pacer",nat:"IND",bat:8,bowl:76},
{id:"maphaka_rr",name:"Kwena Maphaka",role:"Pacer",nat:"SA",bat:8,bowl:76},
{id:"burger_rr",name:"Nandre Burger",role:"Pacer",nat:"SA",bat:10,bowl:78},
{id:"jadeja_rr",name:"Ravindra Jadeja",role:"All-Rounder",nat:"IND",bat:78,bowl:87},
{id:"shanaka_rr",name:"Dasun Shanaka",role:"All-Rounder",nat:"SL",bat:68,bowl:68},
{id:"ferreira_rr",name:"Donovan Ferreira",role:"WK-Batsman",nat:"SA",bat:74,bowl:5},
{id:"bishnoi_rr",name:"Ravi Bishnoi",role:"Spinner",nat:"IND",bat:15,bowl:85},
{id:"sushant_rr",name:"Sushant Mishra",role:"Pacer",nat:"IND",bat:10,bowl:72},
{id:"vignesh_rr",name:"Vignesh Puthur",role:"Pacer",nat:"IND",bat:8,bowl:72},
{id:"yashraj_rr",name:"Yash Raj Punja",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"ravisingh_rr",name:"Ravi Singh",role:"WK-Batsman",nat:"IND",bat:62,bowl:0},
{id:"brijesh_rr",name:"Brijesh Sharma",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"aman_rr",name:"Aman Rao",role:"Batsman",nat:"IND",bat:60,bowl:5},
{id:"milne_rr",name:"Adam Milne",role:"Pacer",nat:"NZ",bat:12,bowl:80},
{id:"kuldeepsen_rr",name:"Kuldeep Sen",role:"Pacer",nat:"IND",bat:8,bowl:75},
],RCB:[
{id:"patidar_rcb",name:"Rajat Patidar",role:"Batsman",nat:"IND",bat:83,bowl:5,isCaptain:true},
{id:"kohli_rcb",name:"Virat Kohli",role:"Batsman",nat:"IND",bat:98,bowl:8},
{id:"timdavid_rcb",name:"Tim David",role:"All-Rounder",nat:"AUS",bat:86,bowl:5},
{id:"devdutt_rcb",name:"Devdutt Padikkal",role:"Batsman",nat:"IND",bat:79,bowl:5},
{id:"salt_rcb",name:"Phil Salt",role:"WK-Batsman",nat:"ENG",bat:84,bowl:0},
{id:"jitesh_rcb",name:"Jitesh Sharma",role:"WK-Batsman",nat:"IND",bat:77,bowl:0},
{id:"krunal_rcb",name:"Krunal Pandya",role:"All-Rounder",nat:"IND",bat:72,bowl:75},
{id:"bethell_rcb",name:"Jacob Bethell",role:"All-Rounder",nat:"ENG",bat:76,bowl:63},
{id:"shepherd_rcb",name:"Romario Shepherd",role:"All-Rounder",nat:"WI",bat:68,bowl:75},
{id:"swapnil_rcb",name:"Swapnil Singh",role:"All-Rounder",nat:"IND",bat:42,bowl:75},
{id:"hazle_rcb",name:"Josh Hazlewood",role:"Pacer",nat:"AUS",bat:15,bowl:90},
{id:"bhuvi_rcb",name:"Bhuvneshwar Kumar",role:"Pacer",nat:"IND",bat:30,bowl:83},
{id:"rasikh_rcb",name:"Rasikh Salam",role:"Pacer",nat:"IND",bat:10,bowl:75},
{id:"yash_rcb",name:"Yash Dayal",role:"Pacer",nat:"IND",bat:8,bowl:77},
{id:"suyash_rcb",name:"Suyash Sharma",role:"Spinner",nat:"IND",bat:15,bowl:77},
{id:"thushara_rcb",name:"Nuwan Thushara",role:"Pacer",nat:"SL",bat:18,bowl:79},
{id:"abhinandan_rcb",name:"Abhinandan Singh",role:"Pacer",nat:"IND",bat:10,bowl:72},
{id:"venky_rcb",name:"Venkatesh Iyer",role:"All-Rounder",nat:"IND",bat:80,bowl:66},
{id:"duffy_rcb",name:"Jacob Duffy",role:"Pacer",nat:"NZ",bat:10,bowl:76},
{id:"mangesh_rcb",name:"Mangesh Yadav",role:"All-Rounder",nat:"IND",bat:42,bowl:74},
{id:"satvik_rcb",name:"Satvik Deswal",role:"All-Rounder",nat:"IND",bat:52,bowl:58},
{id:"cox_rcb",name:"Jordan Cox",role:"Batsman",nat:"ENG",bat:74,bowl:5},
{id:"kanishk_rcb",name:"Kanishk Chouhan",role:"All-Rounder",nat:"IND",bat:35,bowl:60},
{id:"vihaan_rcb",name:"Vihaan Malhotra",role:"All-Rounder",nat:"IND",bat:35,bowl:60},
{id:"ostwal_rcb",name:"Vicky Ostwal",role:"Spinner",nat:"IND",bat:35,bowl:72},
],SRH:[
{id:"head_srh",name:"Travis Head",role:"Batsman",nat:"AUS",bat:90,bowl:30},
{id:"abhi_srh",name:"Abhishek Sharma",role:"All-Rounder",nat:"IND",bat:83,bowl:68},
{id:"aniket_srh",name:"Aniket Verma",role:"Batsman",nat:"IND",bat:72,bowl:5},
{id:"smaran_srh",name:"R Smaran",role:"Batsman",nat:"IND",bat:68,bowl:5},
{id:"ishan_srh",name:"Ishan Kishan",role:"WK-Batsman",nat:"IND",bat:80,bowl:0},
{id:"klaasen_srh",name:"Heinrich Klaasen",role:"WK-Batsman",nat:"SA",bat:90,bowl:0},
{id:"nitish_srh",name:"Nitish Kumar Reddy",role:"All-Rounder",nat:"IND",bat:79,bowl:73},
{id:"harsh_srh",name:"Harsh Dubey",role:"All-Rounder",nat:"IND",bat:55,bowl:65},
{id:"kamindu_srh",name:"Kamindu Mendis",role:"All-Rounder",nat:"SL",bat:80,bowl:72},
{id:"harshal_srh",name:"Harshal Patel",role:"Pacer",nat:"IND",bat:28,bowl:81},
{id:"carse_srh",name:"Brydon Carse",role:"All-Rounder",nat:"ENG",bat:42,bowl:78},
{id:"cummins_srh",name:"Pat Cummins",role:"Pacer",nat:"AUS",bat:52,bowl:93,isCaptain:true},
{id:"unadkat_srh",name:"Jaydev Unadkat",role:"Pacer",nat:"IND",bat:18,bowl:76},
{id:"malinga_srh",name:"Eshan Malinga",role:"Pacer",nat:"SL",bat:10,bowl:76},
{id:"zeeshan_srh",name:"Zeeshan Ansari",role:"Spinner",nat:"IND",bat:15,bowl:74},
{id:"shivang_srh",name:"Shivang Kumar",role:"All-Rounder",nat:"IND",bat:45,bowl:62},
{id:"salil_srh",name:"Salil Arora",role:"WK-Batsman",nat:"IND",bat:60,bowl:0},
{id:"fuletra_srh",name:"Krains Fuletra",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"hinge_srh",name:"Praful Hinge",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"amitk_srh",name:"Amit Kumar",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"onkar_srh",name:"Onkar Tarmale",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"sakib_srh",name:"Sakib Hussain",role:"Pacer",nat:"IND",bat:8,bowl:70},
{id:"living_srh",name:"Liam Livingstone",role:"All-Rounder",nat:"ENG",bat:85,bowl:72},
{id:"mavi_srh",name:"Shivam Mavi",role:"Pacer",nat:"IND",bat:20,bowl:77},
{id:"payne_srh",name:"David Payne",role:"Pacer",nat:"ENG",bat:10,bowl:76},
],};
Object.keys(S).forEach(k=>{if(TEAMS[k])TEAMS[k].players=S[k];});
console.log('IPL 2026 squads Part B loaded');
})();
