// IPL 2026 Official Squads Part A: CSK, DC, GT, KKR, LSG
(function(){
const S={
CSK:[
{id:"rutu_csk",name:"Ruturaj Gaikwad",role:"Batsman",nat:"IND",bat:86,bowl:5,isCaptain:true},
{id:"dhoni_csk",name:"MS Dhoni",role:"WK-Batsman",nat:"IND",bat:80,bowl:0},
{id:"brevis_csk",name:"Dewald Brevis",role:"Batsman",nat:"SA",bat:80,bowl:5},
{id:"mhatre_csk",name:"Ayush Mhatre",role:"Batsman",nat:"IND",bat:74,bowl:5},
{id:"urvil_csk",name:"Urvil Patel",role:"WK-Batsman",nat:"IND",bat:70,bowl:0},
{id:"kamboj_csk",name:"Anshul Kamboj",role:"All-Rounder",nat:"IND",bat:40,bowl:76},
{id:"overton_csk",name:"Jamie Overton",role:"All-Rounder",nat:"ENG",bat:45,bowl:78},
{id:"ghosh_csk",name:"Ramakrishna Ghosh",role:"All-Rounder",nat:"IND",bat:58,bowl:65},
{id:"dube_csk",name:"Shivam Dube",role:"All-Rounder",nat:"IND",bat:77,bowl:68},
{id:"khaleel_csk",name:"Khaleel Ahmed",role:"Pacer",nat:"IND",bat:12,bowl:77},
{id:"noor_csk",name:"Noor Ahmad",role:"Spinner",nat:"AFG",bat:12,bowl:85},
{id:"mukesh_csk",name:"Mukesh Choudhary",role:"Pacer",nat:"IND",bat:8,bowl:74},
{id:"spencer_csk",name:"Spencer Johnson",role:"Pacer",nat:"AUS",bat:15,bowl:81},
{id:"sgopal_csk",name:"Shreyas Gopal",role:"Spinner",nat:"IND",bat:25,bowl:78},
{id:"gurjap_csk",name:"Gurjapneet Singh",role:"Pacer",nat:"IND",bat:8,bowl:72},
{id:"samson_csk",name:"Sanju Samson",role:"WK-Batsman",nat:"IND",bat:87,bowl:0},
{id:"hosein_csk",name:"Akeal Hosein",role:"Spinner",nat:"WI",bat:25,bowl:76},
{id:"pveer_csk",name:"Prashant Veer",role:"All-Rounder",nat:"IND",bat:55,bowl:68},
{id:"kartiks_csk",name:"Kartik Sharma",role:"WK-Batsman",nat:"IND",bat:62,bowl:0},
{id:"short_csk",name:"Matthew Short",role:"All-Rounder",nat:"AUS",bat:74,bowl:30},
{id:"aman_csk",name:"Aman Khan",role:"All-Rounder",nat:"IND",bat:52,bowl:60},
{id:"sarfaraz_csk",name:"Sarfaraz Khan",role:"Batsman",nat:"IND",bat:80,bowl:5},
{id:"rchahar_csk",name:"Rahul Chahar",role:"Spinner",nat:"IND",bat:22,bowl:79},
{id:"henry_csk",name:"Matt Henry",role:"Pacer",nat:"NZ",bat:18,bowl:82},
{id:"foulkes_csk",name:"Zak Foulkes",role:"All-Rounder",nat:"NZ",bat:35,bowl:72},
],DC:[
{id:"rahul_dc",name:"KL Rahul",role:"WK-Batsman",nat:"IND",bat:88,bowl:0,isCaptain:true},
{id:"karun_dc",name:"Karun Nair",role:"Batsman",nat:"IND",bat:76,bowl:5},
{id:"porel_dc",name:"Abishek Porel",role:"WK-Batsman",nat:"IND",bat:74,bowl:0},
{id:"stubbs_dc",name:"Tristan Stubbs",role:"Batsman",nat:"SA",bat:79,bowl:5},
{id:"axar_dc",name:"Axar Patel",role:"All-Rounder",nat:"IND",bat:74,bowl:85},
{id:"rizvi_dc",name:"Sameer Rizvi",role:"Batsman",nat:"IND",bat:76,bowl:5},
{id:"ashutosh_dc",name:"Ashutosh Sharma",role:"Batsman",nat:"IND",bat:74,bowl:5},
{id:"vipraj_dc",name:"Vipraj Nigam",role:"All-Rounder",nat:"IND",bat:18,bowl:74},
{id:"mandal_dc",name:"Ajay Mandal",role:"All-Rounder",nat:"IND",bat:55,bowl:65},
{id:"tripurana_dc",name:"Tripurana Vijay",role:"All-Rounder",nat:"IND",bat:52,bowl:62},
{id:"madhav_dc",name:"Madhav Tiwari",role:"All-Rounder",nat:"IND",bat:45,bowl:60},
{id:"starc_dc",name:"Mitchell Starc",role:"Pacer",nat:"AUS",bat:28,bowl:90},
{id:"nata_dc",name:"T. Natarajan",role:"Pacer",nat:"IND",bat:15,bowl:80},
{id:"mukeshk_dc",name:"Mukesh Kumar",role:"Pacer",nat:"IND",bat:12,bowl:79},
{id:"chameera_dc",name:"Dushmantha Chameera",role:"Pacer",nat:"SL",bat:20,bowl:82},
{id:"kuldeep_dc",name:"Kuldeep Yadav",role:"Spinner",nat:"IND",bat:18,bowl:88},
{id:"nrana_dc",name:"Nitish Rana",role:"Batsman",nat:"IND",bat:76,bowl:30},
{id:"auqib_dc",name:"Auqib Dar",role:"All-Rounder",nat:"IND",bat:55,bowl:68},
{id:"duckett_dc",name:"Ben Duckett",role:"WK-Batsman",nat:"ENG",bat:82,bowl:5},
{id:"miller_dc",name:"David Miller",role:"Batsman",nat:"SA",bat:86,bowl:5},
{id:"nissanka_dc",name:"Pathum Nissanka",role:"Batsman",nat:"SL",bat:80,bowl:10},
{id:"ngidi_dc",name:"Lungi Ngidi",role:"Pacer",nat:"SA",bat:15,bowl:82},
{id:"sahil_dc",name:"Sahil Parakh",role:"Batsman",nat:"IND",bat:62,bowl:5},
{id:"prithvi_dc",name:"Prithvi Shaw",role:"Batsman",nat:"IND",bat:78,bowl:5},
{id:"jamieson_dc",name:"Kyle Jamieson",role:"Pacer",nat:"NZ",bat:40,bowl:82},
],GT:[
{id:"gill_gt",name:"Shubman Gill",role:"Batsman",nat:"IND",bat:92,bowl:5,isCaptain:true},
{id:"sai_gt",name:"B. Sai Sudharsan",role:"Batsman",nat:"IND",bat:84,bowl:5},
{id:"kumar_gt",name:"Kumar Kushagra",role:"WK-Batsman",nat:"IND",bat:65,bowl:0},
{id:"anuj_gt",name:"Anuj Rawat",role:"WK-Batsman",nat:"IND",bat:68,bowl:0},
{id:"buttler_gt",name:"Jos Buttler",role:"WK-Batsman",nat:"ENG",bat:90,bowl:0},
{id:"nishant_gt",name:"Nishant Sindhu",role:"All-Rounder",nat:"IND",bat:62,bowl:65},
{id:"phillips_gt",name:"Glenn Phillips",role:"All-Rounder",nat:"NZ",bat:82,bowl:30},
{id:"sundar_gt",name:"Washington Sundar",role:"All-Rounder",nat:"IND",bat:62,bowl:76},
{id:"arshad_gt",name:"Arshad Khan",role:"Pacer",nat:"IND",bat:15,bowl:74},
{id:"shahrukh_gt",name:"Shahrukh Khan",role:"Batsman",nat:"IND",bat:76,bowl:5},
{id:"tewatia_gt",name:"Rahul Tewatia",role:"All-Rounder",nat:"IND",bat:72,bowl:60},
{id:"rabada_gt",name:"Kagiso Rabada",role:"Pacer",nat:"SA",bat:30,bowl:90},
{id:"siraj_gt",name:"Mohammed Siraj",role:"Pacer",nat:"IND",bat:18,bowl:87},
{id:"prasidh_gt",name:"Prasidh Krishna",role:"Pacer",nat:"IND",bat:12,bowl:81},
{id:"ishant_gt",name:"Ishant Sharma",role:"Pacer",nat:"IND",bat:10,bowl:76},
{id:"gurnoor_gt",name:"Gurnoor Singh Brar",role:"Pacer",nat:"IND",bat:18,bowl:75},
{id:"rashid_gt",name:"Rashid Khan",role:"All-Rounder",nat:"AFG",bat:58,bowl:97},
{id:"manav_gt",name:"Manav Suthar",role:"Spinner",nat:"IND",bat:15,bowl:74},
{id:"saik_gt",name:"Sai Kishore",role:"Spinner",nat:"IND",bat:20,bowl:77},
{id:"jayant_gt",name:"Jayant Yadav",role:"All-Rounder",nat:"IND",bat:48,bowl:73},
{id:"ashok_gt",name:"Ashok Sharma",role:"Pacer",nat:"IND",bat:12,bowl:72},
{id:"holder_gt",name:"Jason Holder",role:"All-Rounder",nat:"WI",bat:60,bowl:78},
{id:"banton_gt",name:"Tom Banton",role:"Batsman",nat:"ENG",bat:74,bowl:5},
{id:"lwood_gt",name:"Luke Wood",role:"Pacer",nat:"ENG",bat:20,bowl:78},
{id:"kulwant_gt",name:"Kulwant Khejroliya",role:"Pacer",nat:"IND",bat:8,bowl:72},
],KKR:[
{id:"rahane_kkr",name:"Ajinkya Rahane",role:"Batsman",nat:"IND",bat:74,bowl:5},
{id:"rinku_kkr",name:"Rinku Singh",role:"Batsman",nat:"IND",bat:83,bowl:5,isCaptain:true},
{id:"angkrish_kkr",name:"Angkrish Raghuvanshi",role:"Batsman",nat:"IND",bat:75,bowl:5},
{id:"manish_kkr",name:"Manish Pandey",role:"Batsman",nat:"IND",bat:74,bowl:5},
{id:"powell_kkr",name:"Rovman Powell",role:"All-Rounder",nat:"WI",bat:80,bowl:5},
{id:"anukul_kkr",name:"Anukul Roy",role:"All-Rounder",nat:"IND",bat:58,bowl:72},
{id:"ramandeep_kkr",name:"Ramandeep Singh",role:"Batsman",nat:"IND",bat:72,bowl:28},
{id:"arora_kkr",name:"Vaibhav Arora",role:"Pacer",nat:"IND",bat:20,bowl:76},
{id:"narine_kkr",name:"Sunil Narine",role:"All-Rounder",nat:"WI",bat:79,bowl:89},
{id:"varun_kkr",name:"Varun Chakravarthy",role:"Spinner",nat:"IND",bat:18,bowl:86},
{id:"saini_kkr",name:"Navdeep Saini",role:"Pacer",nat:"IND",bat:15,bowl:78},
{id:"umran_kkr",name:"Umran Malik",role:"Pacer",nat:"IND",bat:10,bowl:82},
{id:"green_kkr",name:"Cameron Green",role:"All-Rounder",nat:"AUS",bat:78,bowl:72},
{id:"pathirana_kkr",name:"Matheesha Pathirana",role:"Pacer",nat:"SL",bat:12,bowl:90},
{id:"allen_kkr",name:"Finn Allen",role:"WK-Batsman",nat:"NZ",bat:80,bowl:0},
{id:"tejasvi_kkr",name:"Tejasvi Singh",role:"WK-Batsman",nat:"IND",bat:65,bowl:0},
{id:"solanki_kkr",name:"Prashant Solanki",role:"Pacer",nat:"IND",bat:15,bowl:72},
{id:"tyagi_kkr",name:"Kartik Tyagi",role:"Pacer",nat:"IND",bat:10,bowl:73},
{id:"rtripathi_kkr",name:"Rahul Tripathi",role:"Batsman",nat:"IND",bat:74,bowl:5},
{id:"seifert_kkr",name:"Tim Seifert",role:"WK-Batsman",nat:"NZ",bat:70,bowl:0},
{id:"sarthak_kkr",name:"Sarthak Ranjan",role:"All-Rounder",nat:"IND",bat:55,bowl:60},
{id:"daksh_kkr",name:"Daksh Kamra",role:"All-Rounder",nat:"IND",bat:52,bowl:58},
{id:"saurabh_kkr",name:"Saurabh Dubey",role:"Pacer",nat:"IND",bat:10,bowl:72},
{id:"rachin_kkr",name:"Rachin Ravindra",role:"All-Rounder",nat:"NZ",bat:79,bowl:68},
{id:"muzara_kkr",name:"Blessing Muzarabani",role:"Pacer",nat:"ZIM",bat:15,bowl:80},
],LSG:[
{id:"pant_lsg",name:"Rishabh Pant",role:"WK-Batsman",nat:"IND",bat:91,bowl:0,isCaptain:true},
{id:"badoni_lsg",name:"Ayush Badoni",role:"All-Rounder",nat:"IND",bat:76,bowl:5},
{id:"samad_lsg",name:"Abdul Samad",role:"Batsman",nat:"IND",bat:70,bowl:55},
{id:"markram_lsg",name:"Aiden Markram",role:"Batsman",nat:"SA",bat:81,bowl:46},
{id:"himmat_lsg",name:"Himmat Singh",role:"Batsman",nat:"IND",bat:66,bowl:5},
{id:"breetzke_lsg",name:"Matthew Breetzke",role:"Batsman",nat:"SA",bat:74,bowl:5},
{id:"pooran_lsg",name:"Nicholas Pooran",role:"WK-Batsman",nat:"WI",bat:87,bowl:0},
{id:"marsh_lsg",name:"Mitchell Marsh",role:"All-Rounder",nat:"AUS",bat:82,bowl:73},
{id:"shahbaz_lsg",name:"Shahbaz Ahmed",role:"All-Rounder",nat:"IND",bat:68,bowl:73},
{id:"arshin_lsg",name:"Arshin Kulkarni",role:"All-Rounder",nat:"IND",bat:65,bowl:60},
{id:"mayankY_lsg",name:"Mayank Yadav",role:"Pacer",nat:"IND",bat:10,bowl:86},
{id:"avesh_lsg",name:"Avesh Khan",role:"Pacer",nat:"IND",bat:15,bowl:80},
{id:"mohsin_lsg",name:"Mohsin Khan",role:"Pacer",nat:"IND",bat:10,bowl:81},
{id:"siddarth_lsg",name:"M. Siddharth",role:"Spinner",nat:"IND",bat:20,bowl:74},
{id:"digvesh_lsg",name:"Digvesh Rathi",role:"Spinner",nat:"IND",bat:15,bowl:74},
{id:"prince_lsg",name:"Prince Yadav",role:"Pacer",nat:"IND",bat:8,bowl:72},
{id:"akash_lsg",name:"Akash Singh",role:"Pacer",nat:"IND",bat:8,bowl:73},
{id:"arjun_lsg",name:"Arjun Tendulkar",role:"Pacer",nat:"IND",bat:30,bowl:72},
{id:"shami_lsg",name:"Mohammed Shami",role:"Pacer",nat:"IND",bat:18,bowl:93},
{id:"nortje_lsg",name:"Anrich Nortje",role:"Pacer",nat:"SA",bat:15,bowl:88},
{id:"hasaranga_lsg",name:"Wanindu Hasaranga",role:"All-Rounder",nat:"SL",bat:64,bowl:84},
{id:"mukul_lsg",name:"Mukul Choudhary",role:"WK-Batsman",nat:"IND",bat:62,bowl:0},
{id:"naman_lsg",name:"Naman Tiwari",role:"All-Rounder",nat:"IND",bat:52,bowl:62},
{id:"akshat_lsg",name:"Akshat Raghuwanshi",role:"Batsman",nat:"IND",bat:65,bowl:5},
{id:"inglis_lsg",name:"Josh Inglis",role:"WK-Batsman",nat:"AUS",bat:78,bowl:0},
],};
Object.keys(S).forEach(k=>{if(TEAMS[k])TEAMS[k].players=S[k];});
console.log('IPL 2026 squads Part A loaded');
})();
